/**
 * Shared types for the app-pack-generate workflow.
 *
 * Type-only (erased at compile time) — safe to share between the workflow
 * orchestrator, steps, and the route layer without serialization concerns.
 */
import type { AppPackAppDefinition, AppPackDecomposition } from '../../src/domain/app-pack/app-pack-schema';
import type { MaterializeCounts } from '../../src/domain/app-pack/app-pack-materializer';

export interface AppPackGenerateInput {
  /** Business requirement prompt from the platform admin. */
  prompt: string;
  /** Stable pack id (slug). Generated by the route when absent. */
  packId?: string;
  /** Human-readable pack name (falls back to packId). */
  name?: string;
  /** Target tenant slug. */
  tenantSlug: string;
  /** Database connection string (resolved by the route from tenants.db_url or root POSTGRES_URL). */
  dbUrl: string;
  /** When true, runs the deterministic mock pipeline (no OpenAI key needed). */
  mock?: boolean;
  /** OpenAI model for generation steps. */
  model?: string;
  /** OpenAI API key — resolved by the route from DB secrets or env. */
  openaiApiKey?: string | null;
}

/** Progress chunk written to the run's writable stream (SSE payloads). */
export interface ProgressChunk {
  step: string;
  message: string;
  pct: number;
  detail?: Record<string, unknown>;
}

export interface AppPackAppSummary {
  appId: string;
  appName: string;
  department: string;
  w3cStandard: string;
  models: number;
  useCases: number;
  pages: number;
  knowledgeSnippets: number;
  uxStages: number;
}

export interface AppPackGenerateResult {
  stage: 'complete';
  packId: string;
  name: string;
  tenantSlug: string;
  mock: boolean;
  model?: string;
  /** CEO Overview purpose/KPIs from the decomposition. */
  ceoPurpose: string;
  ceoKpis: string[];
  apps: AppPackAppSummary[];
  /** DB write counts from the materializer. */
  counts: MaterializeCounts;
  /** Concatenated ZenStack zmodel sources (for audit / preview). */
  zmodel: string;
}
