import { createApi } from '@reduxjs/toolkit/query/react';
import { baseQuery } from '@shared/store/base-query';
import type { ApiEnvelope } from '@/store/api-types';
import type { AiProviderId, AiProviderStatus, AiModelOption } from '@/store/apis/config-api';

export interface TenantEntry {
  id: string;
  slug: string;
  displayName: string;
  template: string;
  status: 'draft' | 'deploying' | 'live' | 'error';
  vercelProjectId: string | null;
  appUrl: string | null;
  dbUrl: string | null;
  apiKey: string | null;
  primaryColor: string;
  secondaryColor: string;
  faviconData: string | null;
  faviconMimeType: string | null;
  templateMode: 'single' | 'suite';
  appPack: AppPackConfig | null;
  metadata: Record<string, unknown>;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

// ── App Pack (Suite Mode) ──────────────────────────────

/** A single app instance inside a tenant's app pack (suite mode). */
export interface SuiteAppInstance {
  appId: string;
  name: string;
  department: string;
  templateId: string;
  status: 'pending' | 'provisioning' | 'deploying' | 'live' | 'error';
  appUrl: string | null;
  dbUrl: string | null;
  vercelProjectId: string | null;
  /** Per-app brand colors — overrides the tenant default when set. */
  primaryColor?: string | null;
  secondaryColor?: string | null;
  /** Per-app Vercel Deploy Hook URL — this app's own project, distinct from
   *  the tenant-level metadata.config.hooks.deployHookUrl. */
  deployHookUrl?: string | null;
  /** Per-app metadata (schema, pages, nav generated by the app-pack pipeline) */
  metadata?: Record<string, unknown>;
  /** App-scoped config overrides — this app's own values for license, features,
   *  OpenAI key, Google OAuth, database, env, auth, pins, roles. Overrides the
   *  tenant-level metadata.config defaults for this app only. */
  config?: AppScopedConfig;
}

/** App pack configuration stored on a tenant when templateMode === 'suite'. */
export interface AppPackConfig {
  packId: string;
  name: string;
  description: string;
  apps: SuiteAppInstance[];
  ceoOverview: {
    purpose: string;
    kpis: string[];
  };
}

/** Editable subset of the tenant's Google OAuth config (Edit App modal — GCP Credentials step). */
export interface GoogleOAuthConfigPatch {
  enabled?: boolean;
  clientId?: string;
  clientSecret?: string;
  projectId?: string;
  authUri?: string;
  tokenUri?: string;
  gcpAccountEmail?: string;
  supportEmail?: string;
  redirectUris?: string[];
}

/**
 * App-scoped configuration overrides — stored per app_id (SuiteAppInstance.config
 * in the tenant's appPack AND mirrored into the tenant DB's app_settings row
 * "{tenantSlug}__{appId}"). Keys mirror the tenant-level metadata.config shape;
 * when set, an app's value overrides the tenant default for that app only.
 */
export interface AppScopedConfig {
  license?: { key?: string; tier?: string; validUntil?: string; features?: string[] };
  /** Setup token (config.apiKey at tenant level). */
  apiKey?: string;
  openaiApiKey?: string;
  googleAuth?: GoogleOAuthConfigPatch;
  database?: { databaseUrl?: string; pooledUrl?: string; directUrl?: string };
  /** Custom env vars — object form (config.env at tenant level). */
  env?: Record<string, string>;
  auth?: { adminEmail?: string; pinSignInEnabled?: boolean };
  /** Admin PINs (config.pins at tenant level). */
  pins?: string[];
  /** App-scoped role selection — subset of the tenant's role catalog. */
  roles?: { enabled?: string[] };
}

export interface TenantUserView {
  id: string;
  sub: string;
  email: string | null;
  name: string | null;
  tier: string;
  roleCode: string | null;
  isActive: boolean;
  groups: string[];
  permissions: string[];
  lastSeenAt: string | null;
  createdAt: string;
  tenantSlug: string;
}

export interface DeployStatusResponse {
  state: 'READY' | 'ERROR' | 'BUILDING' | 'QUEUED' | 'NOT_FOUND' | 'NO_DEPLOYMENTS';
  slug?: string;
  projectId?: string;
  appUrl?: string;
  note?: string;
  createdAt?: number;
  readyAt?: number;
}

export interface GoogleOAuthProvisionResult {
  clientId: string;
  clientSecret?: string;
  projectId?: string;
  clientSecretJson?: string;
  strategy?: string;
  success?: boolean;
}

export interface NeonProvisionResult {
  success: boolean;
  slug?: string;
  branchId?: string;
  databaseName?: string;
  databaseUrl?: string;
  pooledUrl?: string;
  directUrl?: string;
  formatted?: string;
  envVars?: Record<string, string>;
  connectionStrings?: Record<string, string>;
  message?: string;
}

export interface RenameTenantResult {
  success: boolean;
  tenant: { slug: string };
  previousSlug?: string;
  newSlug?: string;
}

export interface AiFindingsResult {
  findings: Array<{
    type: string;
    message: string;
    severity: 'info' | 'warning' | 'error';
    details?: Record<string, unknown>;
  }>;
}

export interface ScrapeTenantResult {
  scraped: {
    businessName?: string;
    description?: string;
    logoBase64?: string | null;
    brandColors?: { primary: string | null; secondary: string | null; allColors: string[] };
    images?: Array<{ url: string; alt: string }>;
    socialLinks?: Record<string, string>;
    address?: string | null;
    emails?: string[];
    phoneNumbers?: string[];
    textContent?: string;
  };
  recommendedTemplate?: string;
  generatedPrompt?: string;
}

export const tenantApi = createApi({
  reducerPath: 'tenantApi',
  baseQuery,
  tagTypes: ['Tenants', 'TenantUsers', 'AiFindings'],
  endpoints: (builder) => ({
    listTenants: builder.query<ApiEnvelope<{ tenants: TenantEntry[] }>, { status?: string } | void>({
      query: (params) => {
        const searchParams = new URLSearchParams();
        if (params && 'status' in params && params.status) searchParams.set('status', params.status);
        const qs = searchParams.toString();
        return qs ? `admin/tenants?${qs}` : 'admin/tenants';
      },
      providesTags: ['Tenants'],
    }),

    getTenant: builder.query<ApiEnvelope<{ tenant: TenantEntry }>, string>({
      query: (slug) => `admin/tenants/${slug}`,
      providesTags: (_result, _error, slug) => [{ type: 'Tenants', id: slug }],
    }),

    createTenant: builder.mutation<ApiEnvelope<{ tenant: TenantEntry }>, {
      slug: string;
      displayName: string;
      template?: string;
      templateMode?: 'single' | 'suite';
      templates?: string[];
      packMode?: 'predefined' | 'custom';
      primaryColor?: string;
      secondaryColor?: string;
      metadata?: Record<string, unknown>;
      prompt?: string;
    }>({
      query: (body) => ({
        url: 'admin/tenants',
        method: 'POST',
        body,
      }),
      invalidatesTags: ['Tenants'],
    }),

    updateTenant: builder.mutation<ApiEnvelope<{ tenant: TenantEntry }>, {
      slug: string;
      displayName?: string;
      template?: string;
      status?: 'draft' | 'deploying' | 'live' | 'error';
      primaryColor?: string;
      secondaryColor?: string;
      appUrl?: string | null;
      vercelProjectId?: string | null;
      dbUrl?: string | null;
      apiKey?: string | null;
      metadata?: Record<string, unknown>;
    }>({
      query: ({ slug, ...body }) => ({
        url: `admin/tenants/${slug}`,
        method: 'PUT',
        body,
      }),
      invalidatesTags: ['Tenants'],
    }),

    deleteTenant: builder.mutation<ApiEnvelope<{ deleted: boolean }>, string>({
      query: (slug) => ({
        url: `admin/tenants/${slug}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Tenants'],
    }),

    // ── Tenant-scoped Users ─────────────────────────

    listTenantUsers: builder.query<ApiEnvelope<{ users: TenantUserView[] }>, string>({
      query: (slug) => `admin/tenants/${slug}/users`,
      providesTags: (_result, _error, slug) => [{ type: 'TenantUsers', id: slug }],
    }),

    upsertTenantUser: builder.mutation<
      ApiEnvelope<{ id: string; created: boolean }>,
      {
        slug: string;
        sub: string;
        email?: string | null;
        name?: string | null;
        tier?: string;
        roleCode?: string | null;
        groupCodes?: string[];
        pin?: string;
        isActive?: boolean;
      }
    >({
      query: ({ slug, ...body }) => ({
        url: `admin/tenants/${slug}/users`,
        method: 'POST',
        body,
      }),
      invalidatesTags: (_result, _error, { slug }) => [{ type: 'TenantUsers', id: slug }],
    }),

    deleteTenantUser: builder.mutation<ApiEnvelope<{ id: string; deleted: boolean }>, { slug: string; id: string }>({
      query: ({ slug, id }) => ({
        url: `admin/tenants/${slug}/users?id=${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: (_result, _error, { slug }) => [{ type: 'TenantUsers', id: slug }],
    }),

    // ── Tenant Seed & Migrate ──────────────────────────

    seedTenant: builder.mutation<ApiEnvelope<{ seeded: boolean; scope?: 'tenant-wide' | 'full'; pages?: number; navItems?: number; verifiedPages?: number; verifiedNavItems?: number; dbTarget?: 'dedicated' | 'root'; groups?: number; settings?: boolean; adminSeeded?: boolean }>, string>({
      query: (slug) => ({
        url: `admin/tenants/${slug}/seed`,
        method: 'POST',
      }),
      invalidatesTags: ['Tenants'],
    }),

    migrateTenant: builder.mutation<ApiEnvelope<{ migrated: boolean; results?: Record<string, string> }>, string>({
      query: (slug) => ({
        url: `admin/tenants/${slug}/migrate`,
        method: 'POST',
      }),
      invalidatesTags: ['Tenants'],
    }),

    deployTenant: builder.mutation<
      ApiEnvelope<{ deployed: boolean; projectId: string; appUrl: string; envCount: number }>,
      { slug: string; payload?: Record<string, unknown> }
    >({
      query: ({ slug, payload }) => ({
        url: `admin/tenants/${slug}/deploy`,
        method: 'POST',
        body: payload,
      }),
      invalidatesTags: ['Tenants'],
    }),

    /** GET /api/admin/tenants/[slug]/deploy/status — returns latest Vercel
     *  production deployment state. Supports pollingInterval when in-flight. */
    getDeployStatus: builder.query<ApiEnvelope<DeployStatusResponse>, string>({
      query: (slug) => `admin/tenants/${slug}/deploy/status`,
      providesTags: (_result, _error, slug) => [{ type: 'Tenants', id: slug }],
    }),

    // ── Suite App Operations (per-app, suite mode) ─────
    // Mirrors the tenant-level Seed/Migrate/Deploy/Status/Domain/Hooks
    // endpoints above, scoped to a single SuiteAppInstance within a suite.

    seedApp: builder.mutation<ApiEnvelope<{ seeded: boolean; appId: string; pages?: number; navItems?: number; verifiedPages?: number; verifiedNavItems?: number; dbTarget?: 'dedicated' | 'root' }>, { slug: string; appId: string }>({
      query: ({ slug, appId }) => ({
        url: `admin/tenants/${slug}/apps/${appId}`,
        method: 'POST',
      }),
      invalidatesTags: ['Tenants'],
    }),

    migrateApp: builder.mutation<ApiEnvelope<{ migrated: boolean; appId: string; templateId: string; groupsSynced?: number }>, { slug: string; appId: string }>({
      query: ({ slug, appId }) => ({
        url: `admin/tenants/${slug}/apps/${appId}`,
        method: 'PATCH',
      }),
      invalidatesTags: ['Tenants'],
    }),

    deployApp: builder.mutation<ApiEnvelope<{ deployed: boolean; appId: string; projectId: string; appUrl: string; envCount: number }>, { slug: string; appId: string }>({
      query: ({ slug, appId }) => ({
        url: `admin/tenants/${slug}/apps/${appId}`,
        method: 'PUT',
      }),
      invalidatesTags: ['Tenants'],
    }),

    /** GET — lightweight read of the app's currently-stored status (no live Vercel check). */
    getAppStatus: builder.query<ApiEnvelope<{ app: SuiteAppInstance; packId: string; packName: string }>, { slug: string; appId: string }>({
      query: ({ slug, appId }) => `admin/tenants/${slug}/apps/${appId}`,
      providesTags: (_result, _error, { slug }) => [{ type: 'Tenants', id: slug }],
    }),

    /** GET — "Refresh Status": reconciles live Vercel deployment state for this
     *  app's own project and persists status/appUrl back onto the SuiteAppInstance. */
    refreshAppStatus: builder.query<ApiEnvelope<{ appId: string; status: SuiteAppInstance['status']; appUrl: string | null; vercelState: string; note?: string }>, { slug: string; appId: string }>({
      query: ({ slug, appId }) => `admin/tenants/${slug}/apps/${appId}/status`,
      providesTags: (_result, _error, { slug }) => [{ type: 'Tenants', id: slug }],
    }),

    /** PATCH — edit this app's name/department/template/colors/deploy hook. */
    editApp: builder.mutation<
      ApiEnvelope<{ app: SuiteAppInstance }>,
      { slug: string; appId: string; name?: string; department?: string; templateId?: string; primaryColor?: string; secondaryColor?: string; deployHookUrl?: string | null; googleAuth?: GoogleOAuthConfigPatch; config?: AppScopedConfig }
    >({
      query: ({ slug, appId, ...body }) => ({
        url: `admin/tenants/${slug}/apps/${appId}/edit`,
        method: 'PATCH',
        body,
      }),
      invalidatesTags: ['Tenants'],
    }),

    /** POST — "Vercel Save & Push": push all required env vars (Google OAuth
     *  creds, DB URL, PINs, custom env, NEXT_PUBLIC_*) to this app's own
     *  Vercel project from the tenant's saved config. Requires the app to be
     *  deployed (vercelProjectId set). */
    pushAppEnvVars: builder.mutation<
      ApiEnvelope<{ projectId: string; envCount: number; keys: string[] }>,
      { slug: string; appId: string }
    >({
      query: ({ slug, appId }) => ({
        url: `admin/tenants/${slug}/apps/${appId}/vercel-env`,
        method: 'POST',
      }),
      invalidatesTags: ['Tenants'],
    }),

    /** GET — this app's own domain list + Vercel project info (keyed by the app's own vercelProjectId). */
    getAppDomains: builder.query<
      ApiEnvelope<{
        domains: { name: string; verified: boolean; createdAt: string }[];
        projectId: string | null;
        projectInfo?: { name: string; id: string; updatedAt: string } | null;
        autoVercelUrl?: string | null;
        appUrl: string | null;
        note?: string | null;
      }>,
      { slug: string; appId: string }
    >({
      query: ({ slug, appId }) => `admin/tenants/${slug}/apps/${appId}/domains`,
      providesTags: (_result, _error, { slug }) => [{ type: 'Tenants', id: `domain-${slug}` }],
    }),

    /** POST — set/rename this app's custom domain (mirrors setTenantDomain, scoped to the app's own project). */
    setAppDomain: builder.mutation<
      ApiEnvelope<{
        domain: string;
        verified: boolean;
        projectId: string;
        domains: { name: string; verified: boolean; createdAt: string }[];
        appUrl: string | null;
        renamed?: boolean;
        projectName?: string;
        autoVercelUrl?: string | null;
      }>,
      { slug: string; appId: string; domain: string; updateAppUrl?: boolean }
    >({
      query: ({ slug, appId, ...body }) => ({
        url: `admin/tenants/${slug}/apps/${appId}/domains`,
        method: 'POST',
        body,
      }),
      invalidatesTags: (_result, _error, { slug }) => [
        { type: 'Tenants', id: slug },
        { type: 'Tenants', id: `domain-${slug}` },
      ],
    }),

    /** POST — add a new app to an existing suite. */
    addAppToSuite: builder.mutation<
      ApiEnvelope<{ added: boolean; app: SuiteAppInstance; totalApps: number }>,
      { slug: string; appId: string; name: string; department?: string; templateId: string; primaryColor?: string; secondaryColor?: string; deployHookUrl?: string }
    >({
      query: ({ slug, ...body }) => ({
        url: `admin/tenants/${slug}/apps`,
        method: 'POST',
        body,
      }),
      invalidatesTags: ['Tenants'],
    }),

    /** POST — clone an existing suite app (identity + app-scoped content). */
    duplicateApp: builder.mutation<
      ApiEnvelope<{ duplicated: boolean; app: SuiteAppInstance; totalApps: number; copied?: Record<string, number> }>,
      { slug: string; sourceAppId: string; appId: string; name: string; department?: string; templateId?: string; copyContent?: boolean }
    >({
      query: ({ slug, ...body }) => ({
        url: `admin/tenants/${slug}/apps/duplicate`,
        method: 'POST',
        body,
      }),
      invalidatesTags: ['Tenants'],
    }),

    /** DELETE — remove an app from an existing suite. */
    removeAppFromSuite: builder.mutation<
      ApiEnvelope<{ removed: boolean; app: SuiteAppInstance; totalApps: number }>,
      { slug: string; appId: string }
    >({
      query: ({ slug, appId }) => ({
        url: `admin/tenants/${slug}/apps?appId=${encodeURIComponent(appId)}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Tenants'],
    }),

    // ── Custom Domain ─────────────────────────────────

    getTenantDomains: builder.query<
      ApiEnvelope<{
        domains: { name: string; verified: boolean; createdAt: string }[];
        projectId: string | null;
        projectInfo?: { name: string; id: string; updatedAt: string } | null;
        autoVercelUrl?: string | null;
        appUrl: string | null;
        note?: string | null;
        warnings?: string[];
      }>,
      string
    >({
      query: (slug) => `admin/tenants/${slug}/domain`,
      providesTags: (_result, _error, slug) => [{ type: 'Tenants', id: `domain-${slug}` }],
    }),

    // ── Favicon (base64) ─────────────────────────────

    uploadTenantFavicon: builder.mutation<ApiEnvelope<{ message: string }>, { slug: string; data: string; mimeType: string }>({
      query: ({ slug, ...body }) => ({
        url: `admin/tenants/${slug}/favicon`,
        method: 'POST',
        body,
      }),
      invalidatesTags: (_result, _error, { slug }) => [
        { type: 'Tenants', id: slug },
        { type: 'Tenants' },
      ],
    }),

    removeTenantFavicon: builder.mutation<ApiEnvelope<{ message: string }>, string>({
      query: (slug) => ({
        url: `admin/tenants/${slug}/favicon`,
        method: 'DELETE',
      }),
      invalidatesTags: (_result, _error, slug) => [
        { type: 'Tenants', id: slug },
        { type: 'Tenants' },
      ],
    }),

    setTenantDomain: builder.mutation<
      ApiEnvelope<{
        domain: string;
        verified: boolean;
        projectId: string;
        domains: { name: string; verified: boolean; createdAt: string }[];
        appUrl: string | null;
        renamed?: boolean;
        projectName?: string;
        autoVercelUrl?: string | null;
        note?: string;
        projectInfo?: { name: string; id: string; updatedAt: string } | null;
      }>,
      { slug: string; domain: string; updateAppUrl?: boolean }
    >({
      query: ({ slug, ...body }) => ({
        url: `admin/tenants/${slug}/domain`,
        method: 'POST',
        body,
      }),
      invalidatesTags: (_result, _error, { slug }) => [
        { type: 'Tenants', id: slug },
        { type: 'Tenants', id: `domain-${slug}` },
      ],
    }),

    /** POST /api/admin/tenants/scrape — AI scrape of a business URL for the
     *  create-tenant wizard. Read-like POST: no cache invalidation. */
    scrapeTenant: builder.mutation<ApiEnvelope<ScrapeTenantResult>, { url: string }>({
      query: (body) => ({
        url: 'admin/tenants/scrape',
        method: 'POST',
        body,
      }),
    }),

    /** POST to an arbitrary deploy hook URL (Vercel webhook, etc).
     *  Uses queryFn so absolute URLs are supported and the enforce-redux
     *  gate can reach zero violations. Returns unknown because external
     *  webhooks have arbitrary response shapes. */
    triggerDeployHook: builder.mutation<unknown, string>({
      queryFn: async (hookUrl, _api, _extraOptions, baseQuery) => {
        if (hookUrl.startsWith('http')) {
          // External webhook — use native fetch with absolute URL
          try {
            const res = await fetch(hookUrl, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
            });
            if (!res.ok) {
              return { error: { status: res.status, data: await res.text() } };
            }
            const data = await res.json();
            return { data };
          } catch (err) {
            return { error: { status: 500, data: String(err) } };
          }
        }
        // Internal path fallback
        const result = await baseQuery({
          url: hookUrl,
          method: 'POST',
        });
        return result;
      },
    }),

    // ── Provisioning & Admin Operations ───────────────────────

    provisionGoogleOAuth: builder.mutation<ApiEnvelope<GoogleOAuthProvisionResult>, { slug: string; email?: string; redirectUris?: string[] }>({
      query: ({ slug, ...body }) => ({
        url: `admin/tenants/${slug}/provision/google-oauth`,
        method: 'POST',
        body,
      }),
      invalidatesTags: (_result, _error, { slug }) => [{ type: 'Tenants', id: slug }],
    }),

    fetchGoogleOAuthClientInfo: builder.query<ApiEnvelope<Record<string, unknown>>, { slug: string }>({
      query: ({ slug }) => ({
        url: `admin/tenants/${slug}/provision/google-oauth/client-info`,
      }),
    }),

    syncGoogleOAuthClient: builder.mutation<ApiEnvelope<Record<string, unknown>>, { slug: string; patch?: boolean }>({
      query: ({ slug, patch }) => ({
        url: `admin/tenants/${slug}/provision/google-oauth/sync`,
        method: 'POST',
        body: patch ? { patch: true } : undefined,
      }),
      invalidatesTags: (_result, _error, { slug }) => [{ type: 'Tenants', id: slug }],
    }),

    provisionNeon: builder.mutation<ApiEnvelope<NeonProvisionResult>, { slug: string }>({
      query: ({ slug }) => ({
        url: `admin/tenants/${slug}/provision/neon`,
        method: 'POST',
      }),
      invalidatesTags: (_result, _error, { slug }) => [{ type: 'Tenants', id: slug }],
    }),

    testNeonConnection: builder.mutation<ApiEnvelope<{ success: boolean; message?: string }>, { slug: string; dbUrl?: string }>({
      query: ({ slug, dbUrl }) => ({
        url: `admin/tenants/${slug}/provision/neon/test`,
        method: 'POST',
        body: dbUrl ? { dbUrl } : undefined,
      }),
    }),

    checkRedirects: builder.mutation<
      ApiEnvelope<{
        success: boolean;
        message?: string;
        issues?: string[];
        results?: { uri: string; status: number | string }[];
      }>,
      { slug: string }
    >({
      query: ({ slug }) => ({
        url: `admin/tenants/${slug}/provision/check-redirects`,
        method: 'POST',
      }),
    }),

    renameTenant: builder.mutation<ApiEnvelope<RenameTenantResult>, { currentSlug: string; newSlug: string }>({
      query: (body) => ({
        url: `admin/tenants/${body.currentSlug}/rename`,
        method: 'POST',
        body: { newSlug: body.newSlug },
      }),
      invalidatesTags: (_result, _error, { currentSlug }) => [
        { type: 'Tenants', id: currentSlug },
        'Tenants',
      ],
    }),

    /** POST /api/webhooks/vercel — reachability test for the Vercel webhook
     *  endpoint. The route ACKs with a plain-text 200 body, so the response is
     *  read as text instead of JSON. */
    testVercelWebhook: builder.mutation<string, void>({
      query: () => ({
        url: 'webhooks/vercel',
        method: 'POST',
        body: '{}',
        responseHandler: (response: Response) => response.text(),
      }),
    }),

    getAiFindings: builder.query<ApiEnvelope<AiFindingsResult>, void>({
      query: () => 'chat/ai-findings?limit=1',
      providesTags: ['AiFindings'],
    }),

    // ── Admin-scoped AI Provider config — set directly on a tenant/app's own
    // dedicated database from the tenant/app edit modal, so it takes effect
    // on that tenant's live app immediately (see ai-providers.ts). ──
    getTenantAiProviderStatus: builder.query<ApiEnvelope<AiProviderStatus>, { slug: string; appId?: string }>({
      query: ({ slug, appId }) => ({
        url: `admin/tenants/${slug}/ai-provider`,
        params: appId ? { appId } : undefined,
      }),
      providesTags: (_result, _error, { slug, appId }) => [{ type: 'Tenants', id: `ai-provider-${slug}-${appId ?? ''}` }],
    }),
    saveTenantAiProvider: builder.mutation<
      ApiEnvelope<AiProviderStatus>,
      { slug: string; appId?: string; providerId: AiProviderId; apiKey?: string; model?: string; activate?: boolean }
    >({
      query: ({ slug, ...body }) => ({
        url: `admin/tenants/${slug}/ai-provider`,
        method: 'POST',
        body,
      }),
      invalidatesTags: (_result, _error, { slug, appId }) => [{ type: 'Tenants', id: `ai-provider-${slug}-${appId ?? ''}` }],
    }),
    clearTenantAiProviderKey: builder.mutation<ApiEnvelope<AiProviderStatus>, { slug: string; appId?: string; providerId: AiProviderId }>({
      query: ({ slug, ...body }) => ({
        url: `admin/tenants/${slug}/ai-provider`,
        method: 'DELETE',
        body,
      }),
      invalidatesTags: (_result, _error, { slug, appId }) => [{ type: 'Tenants', id: `ai-provider-${slug}-${appId ?? ''}` }],
    }),
    getTenantAiModels: builder.query<ApiEnvelope<{ providerId: AiProviderId; models: AiModelOption[] }>, { slug: string; appId?: string; providerId: AiProviderId }>({
      query: ({ slug, appId, providerId }) => ({
        url: `admin/tenants/${slug}/ai-models`,
        params: { providerId, ...(appId ? { appId } : {}) },
      }),
    }),
    /** POST /api/admin/ai-models-preview — list models for a provider using
     *  an explicit key, before it's saved anywhere (Create App Wizard, where
     *  the app/database don't exist yet to resolve a stored key from). */
    previewAiModels: builder.mutation<ApiEnvelope<{ providerId: AiProviderId; models: AiModelOption[] }>, { providerId: AiProviderId; apiKey?: string }>({
      query: (body) => ({
        url: 'admin/ai-models-preview',
        method: 'POST',
        body,
      }),
    }),
  }),
});

export const {
  useListTenantsQuery,
  useGetTenantQuery,
  useCreateTenantMutation,
  useUpdateTenantMutation,
  useDeleteTenantMutation,
  useListTenantUsersQuery,
  useUpsertTenantUserMutation,
  useDeleteTenantUserMutation,
  useSeedTenantMutation,
  useMigrateTenantMutation,
  useDeployTenantMutation,
  useGetDeployStatusQuery,
  useLazyGetDeployStatusQuery,
  useSeedAppMutation,
  useMigrateAppMutation,
  useDeployAppMutation,
  useGetAppStatusQuery,
  useLazyGetAppStatusQuery,
  useLazyRefreshAppStatusQuery,
  useEditAppMutation,
  usePushAppEnvVarsMutation,
  useGetAppDomainsQuery,
  useLazyGetAppDomainsQuery,
  useSetAppDomainMutation,
  useAddAppToSuiteMutation,
  useDuplicateAppMutation,
  useRemoveAppFromSuiteMutation,
  useLazyGetTenantDomainsQuery,
  useGetTenantDomainsQuery,
  useSetTenantDomainMutation,
  useUploadTenantFaviconMutation,
  useRemoveTenantFaviconMutation,
  useScrapeTenantMutation,
  useTriggerDeployHookMutation,
  useTestVercelWebhookMutation,
  useProvisionGoogleOAuthMutation,
  useFetchGoogleOAuthClientInfoQuery,
  useLazyFetchGoogleOAuthClientInfoQuery,
  useSyncGoogleOAuthClientMutation,
  useProvisionNeonMutation,
  useTestNeonConnectionMutation,
  useCheckRedirectsMutation,
  useRenameTenantMutation,
  useGetAiFindingsQuery,
  useLazyGetTenantQuery,
  useLazyGetAiFindingsQuery,
  useGetTenantAiProviderStatusQuery,
  useSaveTenantAiProviderMutation,
  useClearTenantAiProviderKeyMutation,
  useLazyGetTenantAiModelsQuery,
  usePreviewAiModelsMutation,
} = tenantApi;
