/**
 * Ordered P&L line items matching the Excel workbook layout.
 * `row` is 1-based row number in column B (label column).
 * `layout`: 'rosalita' = 2026 sheet; 'forecast' = 2027/2029/2030 sheets.
 */
export const PNL_LINE_ITEMS = [
  { key: 'header_title', label: "Profit & Loss Projections", header: true },
  { key: 'venue', label: "Rosalita's Cantina", header: true },
  { key: 'gross_income_idr', label: 'Gross Income IDR', header: true },
  { key: 'target_guests_day', label: 'Target Number of Guests - per day', row: { rosalita: 8, forecast: 9 } },
  { key: 'target_guests_month', label: 'Target Number of Guests - per month', row: { rosalita: 9, forecast: 10 } },
  { key: 'target_spend_net', label: 'Target Spend - Net of Tax & Service', row: { rosalita: 10, forecast: 11 } },
  { key: 'target_spend_gross', label: 'Target Spend - Including Tax & Service', row: { rosalita: 11, forecast: 12 } },
  { key: 'target_revenue_food', label: 'Target Revenue - Food', row: { rosalita: 12, forecast: 13 } },
  { key: 'target_revenue_beverage', label: 'Target Revenue - Beverage', row: { rosalita: 13, forecast: 14 } },
  { key: 'gofood_revenue', label: 'GoFood/Chickenria Container Dewi Sri', row: { rosalita: 14, forecast: 15 } },
  { key: 'starcard_provision', label: 'StarCARD Cash Back Provision/Discounts/FOC', row: { rosalita: 15, forecast: 16 }, altLabel: 'StarCARD Cash Back Provision' },
  { key: 'net_income_pre_tax', label: 'Net Income pre Tax/Service', row: { rosalita: 16, forecast: 17 } },
  { key: 'net_income_pre_tax_accum', label: 'Accumulated Net Income pre Tax/Service', row: { rosalita: 17, forecast: 18 } },
  { key: 'total_income_per_day', label: 'Total Income per Day', row: { rosalita: 20, forecast: 23 } },
  { key: 'total_guests_month', label: 'Total Guests per month', row: { rosalita: 22, forecast: 19 } },
  { key: 'spend_per_guest', label: 'Spend per Guest - Actual', row: { rosalita: 24, forecast: null } },
  { key: 'taxes_service', label: 'Taxes and Service Charge Provision', row: { rosalita: 25, forecast: 20 } },
  { key: 'total_income_idr', label: 'Total Income IDR', row: { rosalita: 27, forecast: 21 } },
  { key: 'total_income_accum', label: 'Total Income IDR - Accumulated', row: { rosalita: 28, forecast: 22 } },
  { key: 'less_direct_costs', label: 'Less Direct Costs', header: true },
  { key: 'purchases_food', label: 'Purchases Food', row: { rosalita: 32, forecast: 25 } },
  { key: 'purchases_beverage', label: 'Purchases Beverage & Other', row: { rosalita: 33, forecast: 26 } },
  { key: 'costs_entertainment', label: 'Costs of Entertainment', row: { rosalita: 34, forecast: 27 } },
  { key: 'other_direct', label: 'Other Direct Expenses', row: { rosalita: 35, forecast: 28 } },
  { key: 'total_direct_costs', label: 'Total Direct Costs', row: { rosalita: 36, forecast: 29 } },
  { key: 'gross_profit', label: 'Gross Profit', row: { rosalita: 38, forecast: 30 } },
  { key: 'gross_profit_margin', label: 'Gross Profit Margin', row: { rosalita: 39, forecast: 31 }, pct: true },
  { key: 'overhead_expenses', label: 'Overhead Expenses', header: true },
  { key: 'salary_wages_pkg', label: 'Salary & Wages Package', header: true },
  { key: 'staff_mgmt_count', label: 'Staff Wages - Management', row: { rosalita: 44, forecast: 34 } },
  { key: 'staff_mgmt_cost', label: 'Staff Wages - Management', row: { rosalita: 45, forecast: 35 }, sub: true },
  { key: 'staff_dj_count', label: 'Staff Wages - Music/DJ', row: { rosalita: 46, forecast: null } },
  { key: 'staff_dj_cost', label: 'Staff Wages - Music/DJ', row: { rosalita: 47, forecast: null }, sub: true },
  { key: 'staff_reception_count', label: 'Staff Wages - Reception/Cashier/Supervisor', row: { rosalita: 48, forecast: 36 } },
  { key: 'staff_reception_cost', label: 'Staff Wages - Reception/Cashier/Supervisor', row: { rosalita: 49, forecast: 37 }, sub: true },
  { key: 'staff_waiter_count', label: 'Staff Wages - Waiter/Waitress', row: { rosalita: 50, forecast: 38 } },
  { key: 'staff_waiter_cost', label: 'Staff Wages - Waiter/Waitress', row: { rosalita: 51, forecast: 39 }, sub: true },
  { key: 'staff_bar_count', label: 'Staff Wages - Bar Staff', row: { rosalita: 52, forecast: 40 } },
  { key: 'staff_bar_cost', label: 'Staff Wages - Bar Staff', row: { rosalita: 53, forecast: 41 }, sub: true },
  { key: 'staff_kitchen_count', label: 'Staff Wages - Kitchen', row: { rosalita: 54, forecast: 42 } },
  { key: 'staff_kitchen_cost', label: 'Staff Wages - Kitchen', row: { rosalita: 55, forecast: 43 }, sub: true },
  { key: 'staff_store_count', label: 'Staff Wages - Store/Cleaning & GRO', row: { rosalita: 56, forecast: null } },
  { key: 'staff_store_cost', label: 'Staff Wages - Store/Cleaning & GRO', row: { rosalita: 57, forecast: null }, sub: true },
  { key: 'staff_travel', label: 'Staff Travel/Meal/PBJS etc', row: { rosalita: 58, forecast: 44 } },
  { key: 'total_staff_fte', label: 'Total Staff - Full Time', row: { rosalita: 59, forecast: 45 } },
  { key: 'total_staff_cost', label: 'Total Staff - Full Time', row: { rosalita: 60, forecast: null }, sub: true, altLabel: 'Total Staff Cost' },
  { key: 'sales_marketing', label: 'Sales & Marketing Costs', header: true },
  { key: 'advertising', label: 'Advertising & Promotion', row: { rosalita: 64, forecast: 49 } },
  { key: 'marketing_material', label: 'Marketing Material/Printing etc', row: { rosalita: 65, forecast: 50 } },
  { key: 'property_header', label: 'Property Rents, Repairs & Maintenance', header: true },
  { key: 'rents_leases', label: 'Rents & Leases', row: { rosalita: 68, forecast: 53 } },
  { key: 'body_corporate', label: 'Body Corporate', row: { rosalita: 69, forecast: 54 }, altLabel: 'Body Corporate & Maintenance' },
  { key: 'repairs', label: 'Repairs & Maintenance/Replacements', row: { rosalita: 70, forecast: 55 } },
  { key: 'electric_gas', label: 'Electric & Gas', row: { rosalita: 71, forecast: 56 } },
  { key: 'overhead_general', label: 'Overhead & General Expenses', header: true },
  { key: 'admin_fees', label: 'Admin/Management Fees', row: { rosalita: 74, forecast: 59 }, altLabel: 'Management' },
  { key: 'bank_fees', label: 'Bank & Card Fees/Interest', row: { rosalita: 75, forecast: 60 } },
  { key: 'communication', label: 'Communication Costs', row: { rosalita: 76, forecast: null } },
  { key: 'sundry', label: 'Sundry Overhead & Costs', row: { rosalita: 77, forecast: 61 } },
  { key: 'total_overhead', label: 'Total Overhead Expenses', row: { rosalita: 78, forecast: 62 } },
  { key: 'total_expenses', label: 'Total Expenses', row: { rosalita: 80, forecast: 63 } },
  { key: 'starpoints_addback', label: 'Add Back StarPOINTS Benefit', row: { rosalita: 83, forecast: 65 }, altLabel: 'Add Back StarCARD Benefit' },
  { key: 'ebitda', label: 'EBITDA', row: { rosalita: 84, forecast: 66 } },
  { key: 'ebitda_margin', label: 'EBITDA Margin', row: { rosalita: 85, forecast: 67 }, pct: true },
  { key: 'breakeven_header', label: 'Breakeven Calculation', header: true },
  { key: 'fixed_costs', label: 'Fixed Costs', row: { rosalita: 91, forecast: 71 } },
  { key: 'variable_costs', label: 'Variable Costs', row: { rosalita: 92, forecast: 72 } },
  { key: 'gross_income_req_month', label: 'Gross Income Requirement per month', row: { rosalita: 93, forecast: 74 }, altLabel: 'Revenue Requirement per month' },
  { key: 'gross_revenue_req_day', label: 'Gross Revenue Requirement per Day', row: { rosalita: 94, forecast: 75 }, altLabel: 'Revenue Requirement per Day' },
  { key: 'gross_income_req_day_budget', label: 'Gross Income Requirement per Day - Budgeted', row: { rosalita: 95, forecast: null } },
  { key: 'breakeven_actual', label: 'Actual', row: { rosalita: 96, forecast: null } },
];

export function layoutForSheet(sheetName) {
  return sheetName === 'Rosalita' ? 'rosalita' : 'forecast';
}

export function rowForItem(item, layout) {
  if (!item.row) return null;
  return item.row[layout] ?? null;
}
